version: '3.8'

services:
  mitienda-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mitienda-catalogo-pos
    restart: always
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
